return {
  'sitiom/nvim-numbertoggle',
  require 'plugins.neoformat',
  require 'plugins.comment',
  require 'plugins.lualine',
  require 'plugins.barbar',
  require 'plugins.undotree',
  require 'plugins.tagbar',
  require 'plugins.noice',
  require 'plugins.easymotion',
  require 'plugins.gitsigns',
  require 'plugins.fugitive',
  require 'plugins.lazygit',
  require 'plugins.whichkey',
  require 'plugins.todo-comments',
  require 'plugins.mason',
  require 'plugins.nvim-dap',
  require 'plugins.telescope',
  require 'plugins.overseer',
  require 'plugins.toggleterm',
  require 'plugins.nvim-treesitter',
  require 'plugins.colorscheme',
  -- require 'plugins.nvim-cmp',
  require 'plugins.nvim-lspconfig',
  require 'plugins.dashboard',
  require 'plugins.neorg',
  require 'plugins.headlines',
  'godlygeek/tabular',
  'plasticboy/vim-markdown',
  'iamcco/markdown-preview.vim',
  require 'plugins.neovim-cmake',
  'mhinz/neovim-remote',
  'lervag/vimtex',
  'alec-gibson/nvim-tetris',

  'tmux-plugins/vim-tmux-focus-events',
  'roxma/vim-tmux-clipboard',
  'christoomey/vim-tmux-navigator',
}
